"""empty message

Revision ID: 1731d5d1bef7
Revises: 720277f7abab
Create Date: 2024-05-30 10:34:45.828908

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1731d5d1bef7"
down_revision: Union[str, None] = "720277f7abab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("log_entries", sa.Column("event_id", sa.String(), nullable=True))
    op.create_index(op.f("ix_log_entries_event_id"), "log_entries", ["event_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_log_entries_event_id"), table_name="log_entries")
    op.drop_column("log_entries", "event_id")
    # ### end Alembic commands ###
