"""empty message

Revision ID: 720277f7abab
Revises:
Create Date: 2024-05-27 13:43:11.646918

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "720277f7abab"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "log_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("level", sa.String(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_log_entries_id"), "log_entries", ["id"], unique=False)
    op.create_index(op.f("ix_log_entries_level"), "log_entries", ["level"], unique=False)
    op.create_index(op.f("ix_log_entries_message"), "log_entries", ["message"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_log_entries_message"), table_name="log_entries")
    op.drop_index(op.f("ix_log_entries_level"), table_name="log_entries")
    op.drop_index(op.f("ix_log_entries_id"), table_name="log_entries")
    op.drop_table("log_entries")
    # ### end Alembic commands ###
